### ISSUE TITLE
Latest updated from exoplanet removes gp module.

### ISSUE THREAD

**Issue by jejjohnson** [bmorris3/dot#42]
**Issue**

Got an error when using the latest exoplanet package (`0.4.0`) 

```bash
File "/home/jemanjohnson34/projects/dot/dot/model.py", line 5, in <module>
    from exoplanet.gp import terms, GP
  File "/opt/conda/envs/dotenv_gcp/lib/python3.8/site-packages/exoplanet/gp.py", line 1, in <module>
    raise ImportError(
ImportError: The 'gp' submodule has been removed; use 'celerite2' instead: https://github.com/dfm/celerite2
```

After checking the [release](https://github.com/exoplanet-dev/exoplanet/releases/tag/v0.4.0), found that the latest update has dropped the gp from the package and instead uses the [`celerite2` ](https://celerite2.readthedocs.io/en/latest/)package. 

**Noticeable Code Change**

The API has changed slightly as there is no `gp.marginal` method for us like in [version 0.3](https://docs.exoplanet.codes/en/v0.3.0/user/api/#scalable-gaussian-processes). Will have to go through the [new tutorial](https://celerite2.readthedocs.io/en/latest/tutorials/first/) to see what's changed.

**Suggestions**

1. We can go through and update everything to the newest version, `0.4`.
2. We just use the previous version, `0.3`. 
3. I couldn't find the exoplanet requirement nor an explicit requirements file in the `celerite` branch so I guess that maybe why I stumbled on this as I was using an updated `environment_gcp.yml` file.

**Fix**

For now, I made the exoplanet package `0.3` for now. Below is the `environment_gcp.yml` file.

<details>

```yml
name: dotenv_gcp
channels:
  - anaconda
dependencies:
  - python=3.8
  - numpy>=1.19
  - pandas>=1.1
  - astropy>3.2.1
  - conda-forge::lightkurve
  - h5py>=2.10
  - conda-forge::pymc3
  - conda-forge::celerite
  - matplotlib>=3.3
  - seaborn>=0.11
  - pip
  - pip:
    - wandb
    - tqdm
    - mypy
    - corner
    - exoplanet==0.3.3
    - google-cloud-storage>1.16
```
</details>
